version: '3.7'

services:
  nginx:
    image: nginx:latest
    ports:
      - ${NGINX_PORT-8003}:80
    volumes:
      - ../global-files/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - swoole
    ulimits:
      nproc: 819200
      nofile: 819200

  swoole:
    build:
      context: .
      dockerfile: ../images/swoole/Dockerfile
    working_dir: /app
    environment:
      APP_ENV: prod
      APP_TYPE: swoole
    volumes:
      - ../../:/app:cached
      - ../global-files/php.ini:/usr/local/etc/php/php.ini
